name: Staging Deploy

on:
  push:
    branches:
      - master

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    environment:
      name: staging
      url: https://stg.bbun.gistory.me

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"
          cache: true

      - uses: actions/cache@v4
        with:
          path: |
            .dart_tool
            !.dart_tool/**/*.snapshot
          key: ${{ runner.os }}-dart-tool-${{ hashFiles('pubspec.lock') }}

      - name: Copy dotenv
        run: |
          echo '${{ vars.DOTENV }}' > .env

      - name: Generate files
        run: |
          dart run slang
          dart run build_runner build --delete-conflicting-outputs

      - name: build
        run: |
          flutter build web

      - name: Deploy to production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy build --project-name=bbunline-fe-stg
